# Generated by Django 4.2.3 on 2023-07-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_db_api", "0005_alter_movie_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="value",
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
