# Generated by Django 4.2.3 on 2023-07-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_db_api", "0007_alter_movie_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="genre",
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(null=True, to="movie_db_api.genre"),
        ),
    ]
