# Generated by Django 4.2.3 on 2023-07-18 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie_db_api", "0008_remove_movie_genre_movie_genres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="genres",
            new_name="genre",
        ),
    ]
