# Generated by Django 4.2.3 on 2023-07-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_db_api", "0009_rename_genres_movie_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.ManyToManyField(to="movie_db_api.genre"),
        ),
    ]
