# Generated by Django 4.2.3 on 2023-07-19 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movie_db_api", "0010_alter_movie_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_ratings",
                        to="movie_db_api.movie",
                    ),
                ),
                (
                    "rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movie_db_api.rating",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movie_ratings",
                to="movie_db_api.movierating",
            ),
        ),
    ]
