# Generated by Django 4.2.3 on 2023-07-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movie_db_api", "0012_remove_movie_rating_rating_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movierating",
            name="rating",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_ratings",
                to="movie_db_api.rating",
            ),
        ),
    ]
